# Generated by Django 2.1.7 on 2019-03-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepost',
            name='make',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
