# Generated by Django 2.1.7 on 2019-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehiclepost_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepost',
            name='mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclepost',
            name='model',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclepost',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
