# Generated by Django 2.1.7 on 2019-03-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190329_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepost',
            name='description',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclepost',
            name='price',
            field=models.IntegerField(default=12000),
            preserve_default=False,
        ),
    ]
