# Generated by Django 2.1.7 on 2019-04-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190329_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
