# Generated by Django 5.0 on 2024-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_buyvehicle_id_alter_vehiclepost_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.FloatField()),
                ('horsepower', models.IntegerField()),
                ('city_mpg', models.FloatField()),
            ],
        ),
    ]
